apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-kube-state-metrics
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kubeStateMetrics.type }}
  selector:
    app.kubernetes.io/name: kube-state-metrics
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.kubeStateMetrics.ports | toYaml | nindent 2 -}}