apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychart.fullname" . }}-doit-kube-state-metrics
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.doitKubeStateMetrics.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychart.fullname" . }}-doit-collector
  labels:
    app: doit-collector
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.doitCollector.serviceAccount.annotations | nindent 4 }}